from tkinter import *
# import expdate
import mysql.connector
db_connect=mysql.connector.connect(host="localhost",user="root",password="maan",database="expense")
db_cursor=db_connect.cursor()

def add_expense(day,month,year):
    print("add exp")
    window=Tk()
    window.title("Expense list")   
    l_message=Label(window)
    l_msg=Label(window)
    print(day)
    print(month)
    print(year)
    l_trans=Label(window,text="Transport :")
    e_trans=Entry(window)
    l_food=Label(window,text="Food :")
    e_food=Entry(window)
    l_home=Label(window,text="Home :")
    e_home=Entry(window)
    l_ent=Label(window,text="Entertainment :")
    e_ent=Entry(window)
    l_utl=Label(window,text="Utilities :")
    e_utl=Entry(window)
    l_health=Label(window,text="Health :")
    e_health=Entry(window)
    l_oth=Label(window,text="Others :")
    e_oth=Entry(window)
    def enter_data():
        trans=int(e_trans.get())
        food=int(e_food.get())
        home=int(e_home.get())
        ent=int(e_ent.get())
        utl=int(e_utl.get())
        health=int(e_health.get())
        other=int(e_oth.get())
        total=trans+food+home+ent+utl+health+other
        print(total)
        db_cursor.execute(f"insert into daily(day,month,year,Transport,Food,Home,Entertainment,Utilities,Health,Others,Total)values('{day}','{month}','{year}','{trans}','{food}','{home}','{ent}','{utl}','{health}','{other}','{total}')")
        db_connect.commit()
        db_connect.close()
        l_msg.config(text=" Data has been Updated!")

    add_exp= Button(window, text= "add expense", command= enter_data)
    add_exp.pack(pady=30)

    l_trans.place(x =20,y=50)
    e_trans.place(x =120,y=50)
    l_food.place(x =20,y=70)
    e_food.place(x =120,y=70)
    l_home.place(x =20,y=90)
    e_home.place(x =120,y=90)
    l_ent.place(x =20,y=110)
    e_ent.place(x =120,y=110)
    l_utl.place(x =20,y=130)
    e_utl.place(x =120,y=130)
    l_health.place(x =20,y=150)
    e_health.place(x =120,y=150)
    l_oth.place(x =20,y=170)
    e_oth.place(x =120,y=170)
    l_message.place(x=50,y=100)
    l_msg.place(x=120,y=170)
    exit_button = Button(window, text="Exit", command=window.destroy)
    exit_button.pack(pady=200)
    window.geometry("800x800")
    window.mainloop()

